# [gae 設定の説明](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml?hl=ja)

# このruntimeを元に自動的に値がNODE_ENVなどの値が設定される。
runtime: nodejs16
# 無料枠
env: standard

# 無料枠 
instance_class: F1
service: default

env_variables:
  # [gae gcs](https://cloud.google.com/appengine/docs/flexible/nodejs/using-cloud-storage?hl=ja)
  GCLOUD_STORAGE_BUCKET: YOUR_BUCKET_NAME
  PGUSER: your_pguser
  PGHOST: your_host
  PGPASSWORD: your_password
  PGDATABASE: your_database
  PGPORT: 5432
  VIRTUAL_ENV: gae
  MJ_APIKEY_PUBLIC: YOUR_PUBLIC_KEY
  MJ_APIKEY_PRIVATE: YOUR_PRIVATE_KEY
